### ISSUE TITLE
你好，我这边aht21芯片不太好焊接，所以我想要一下您历史版本，没有aht21库的版本可以吗

### ISSUE THREAD

**Issue by hwxchy** [YuzukiHD/Contemporary-Art-Driver#1]
你好，我这边aht21芯片不太好焊接，所以我想要一下您历史版本，没有aht21库的版本可以吗。可以的话发一份到我的游戏hwxchy@qq.com 已点star

**Comment by YuzukiTsuru** [comment]
https://github.com/YuzukiHD/Contemporary-Art-Driver/tree/20678fd276412491f6d370ddfd41d93bff568283

Git可以查看历史
