### ISSUE TITLE
你好，关于屏幕乱码问题

### ISSUE THREAD

**Issue by hwxchy** [YuzukiHD/Contemporary-Art-Driver#2]
我这边遇到点问题，就是程序烧录进去后，屏幕是乱码，检查过焊接是没问题的。两块测试板都是如此。购买的也是ssd1306 0.9114pin的屏幕 走的是i2c的协议。代码就是您昨天给的无温湿度的版本。

**Comment by hwxchy** [comment]
想请您发一份您的hex文件给我，不带温湿度的。我排除下是否是软件问题 邮箱hwxchy@qq.com

**Comment by hwxchy** [comment]
回头请您喝杯奶茶 您看可以吗

**Comment by YuzukiTsuru** [comment]
屏幕乱码是编码选择问题，keil这个问题诟病很久了，可能是我上传github编码改变了

**Comment by hwxchy** [comment]
所以方便加一个联系方式吗，您通过qq或者微信传一个源文件包给我可以吗。谢谢您

**Comment by YuzukiTsuru** [comment]
[CAD.zip](https://github.com/YuzukiHD/Contemporary-Art-Driver/files/8339403/CAD.zip)

**Comment by YuzukiTsuru** [comment]
[CAD.zip](https://github.com/YuzukiHD/Contemporary-Art-Driver/files/8339406/CAD.zip)
