### ISSUE TITLE
对的 还是我这个老菜比。

### ISSUE THREAD

**Issue by hwxchy** [YuzukiHD/Contemporary-Art-Driver#3]
你好，很抱歉打搅您，我已经被这个艺术搞得自己快变艺术了。我这边用了您给的hex文件也还是乱码。我甚至还换了家淘宝店购买屏幕都不行。您这边方便给一下屏幕、字库、主控、的购买链接吗。我完全按照您的步骤做一遍看看还行不行。

**Comment by YuzukiTsuru** [comment]
方便的话发一下图片我看看吧，不同乱码有不同的问题

**Comment by hwxchy** [comment]
![4934055BDB531316B557E3A8665AF23C](https://user-images.githubusercontent.com/44592155/159975949-618836a1-82b0-4d46-9303-3aa251c344a4.png)
![397a6b1d8beafcea3fe0e3a8923f91a](https://user-images.githubusercontent.com/44592155/159976397-f50ae15e-8495-4c06-b50c-9a4dee2cf334.jpg)
![40a5ae51087abb7ef8a4cf713a19757](https://user-images.githubusercontent.com/44592155/159976411-9cef2dcd-eb3d-4cea-be8a-d42e5475375d.jpg)
![IMG_1196](https://user-images.githubusercontent.com/44592155/159976484-df8a407a-fb81-4d13-8317-87d684a6709f.JPG)

方便留个联系方式吗，我最后要是还解决不了的话，想从您这购买点艺术，

**Comment by hwxchy** [comment]
里面是第一个语句和最后一个语句的乱码，还有屏幕型号。字库用的GT20L16P1Y 型号，立创商城的。主控是stc8g1k08-38i-qfn20也是立创商城买的。

**Comment by hwxchy** [comment]
![9F83F4E263902C4CA3F78B0359938437](https://user-images.githubusercontent.com/44592155/160072998-f4832761-ad3c-46c3-8f54-17a505829509.png)

![0BA0F3615728EF8DE2792B54EFC0449B](https://user-images.githubusercontent.com/44592155/160073002-ff007f6e-52d3-427d-a118-8b62d6f617d0.png)
![98583A46156378C07F42C74820CA2313](https://user-images.githubusercontent.com/44592155/160073015-527bfbf8-cace-446c-a2fa-50a805e87557.png)
![5097A595A2297D6900247039ED64E3D7](https://user-images.githubusercontent.com/44592155/160073028-f737bd82-6bb0-4ac5-8115-f7b7dbc87ec7.png)
![Uploading 14C9658D5E0283A7E85FF552F1646218.png…]()

**Comment by YuzukiTsuru** [comment]
屏幕问题，屏幕驱动方式不太一样，可以找这家屏幕提供商索要驱动代码，我的OLED是中景园的蓝色和黄色的

**Comment by hwxchy** [comment]
好了 解决了，问题是字库的，你给的是p1y的字库，包括立创eda里面的也是，我换了s1y的字库就行了。坐等大佬开源随机生产语句的代码。谢谢大佬了

**Comment by YuzukiTsuru** [comment]
> 

还有这事？我都没发现

**Comment by hwxchy** [comment]
还有一个小问题就是带dht21的库的目前的包，是编译不通过的。有两个error，我尝试修改，发现不行。

**Comment by YuzukiTsuru** [comment]
> 还有一个小问题就是带dht21的库的目前的包，是编译不通过的。有两个error，我尝试修改，发现不行。

是有问题，我还在调试那个传感器

**Comment by hwxchy** [comment]
好的 坐等大佬修改好。
